# Generated by Django 5.2.5 on 2025-11-16 16:27

import uuid

import django.core.validators, django.db.models.deletion
from django.db import migrations, models

import gestion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "acreditacion",
                    models.CharField(
                        blank=True, default=None, max_length=8, null=True, unique=True
                    ),
                ),
                (
                    "dni",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOMBRE", "Hombre"),
                            ("MUJER", "Mujer"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "talla_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        null=True,
                        upload_to=gestion.models.ruta_cv,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            gestion.models.validador_pdf,
                        ],
                    ),
                ),
                ("compartir_cv", models.BooleanField(default=False)),
                ("aceptado", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RestriccionAlimentaria",
            fields=[
                ("id_restriccion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Restricción Alimentaria",
                "verbose_name_plural": "Restricciones Alimentarias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPase",
            fields=[
                ("id_tipo_pase", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("inicio_validez", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Tipo de Pase",
                "verbose_name_plural": "Tipos de Pase",
                "ordering": ["inicio_validez"],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gestion.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentores",
                "abstract": False,
            },
            bases=("gestion.persona",),
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gestion.persona",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "ano_nacimiento",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1970, "El año debe ser mayor o igual a 1970."
                            ),
                            django.core.validators.MaxValueValidator(
                                2015, "El año debe ser menor o igual a 2015."
                            ),
                        ],
                    ),
                ),
                (
                    "nivel_estudio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FORMACION_PROFESIONAL", "Formación Profesional"),
                            ("UNIVERSIDAD", "Universidad"),
                            ("MASTER", "Máster"),
                            ("OTRO", "Otro (Especificar en notas)"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "nombre_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "centro_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("curso", models.CharField(blank=True, max_length=128, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=128, null=True)),
                ("quiere_creditos", models.BooleanField(default=False)),
                ("motivacion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "abstract": False,
            },
            bases=("gestion.persona",),
        ),
        migrations.AddField(
            model_name="persona",
            name="restricciones_alimentarias",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)ss",
                to="gestion.restriccionalimentaria",
            ),
        ),
        migrations.CreateModel(
            name="Patrocinador",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "acreditacion",
                    models.CharField(
                        blank=True, default=None, max_length=8, null=True, unique=True
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                (
                    "restricciones_alimentarias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)ss",
                        to="gestion.restriccionalimentaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Pase",
            fields=[
                ("id_pase", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="gestion.persona",
                    ),
                ),
                (
                    "tipo_pase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="gestion.tipopase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase",
                "verbose_name_plural": "Pases",
                "ordering": ["fecha"],
                "unique_together": {("persona", "tipo_pase", "fecha")},
            },
        ),
        migrations.RemoveField(
            model_name="persona",
            name="aceptado",
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_aceptacion",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_confirmacion_plaza",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_registro",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_verificacion_correo",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="Presencia",
            fields=[
                ("id_presencia", models.AutoField(primary_key=True, serialize=False)),
                ("entrada", models.DateTimeField(blank=True, default=None, null=True)),
                ("salida", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempo_acceso",
                        to="gestion.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presencia",
                "verbose_name_plural": "Presencias",
                "unique_together": {("persona", "entrada", "salida")},
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VERIFICACION", "Verificación correo"),
                            ("CONFIRMACION", "Confirmación plaza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("tiempo_validez_minutos", models.PositiveIntegerField()),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="gestion.persona",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="participante",
            name="ano_nacimiento",
            field=models.PositiveIntegerField(
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(
                        1970, "El año debe ser mayor o igual a 1970."
                    ),
                    django.core.validators.MaxValueValidator(
                        2015, "El año debe ser menor o igual a 2015."
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="centro_estudio",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="ciudad",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="curso",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="motivacion",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nivel_estudio",
            field=models.CharField(
                choices=[
                    ("FORMACION_PROFESIONAL", "Formación Profesional"),
                    ("UNIVERSIDAD", "Universidad"),
                    ("MASTER", "Máster"),
                    ("OTRO", "Otro (Especificar en notas)"),
                ],
                max_length=128,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nombre_estudio",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="participante",
            name="telefono",
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dni",
            field=models.CharField(max_length=9, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[("HOMBRE", "Hombre"), ("MUJER", "Mujer"), ("OTRO", "Otro")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="talla_camiseta",
            field=models.CharField(
                choices=[
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.RemoveField(
            model_name="token",
            name="tiempo_validez_minutos",
        ),
        migrations.AlterModelOptions(
            name="participante",
            options={
                "permissions": [
                    ("aceptar_participante", "Aceptar Participante"),
                    ("ver_cv_participante", "Ver el CV de Participante"),
                    (
                        "ver_dni_telefono_participante",
                        "Ver el DNI y el teléfono de Participante",
                    ),
                ],
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
        ),
        migrations.AlterModelOptions(
            name="persona",
            options={"ordering": ["-fecha_registro"]},
        ),
        migrations.AlterField(
            model_name="participante",
            name="centro_estudio",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Centro de estudios"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="ciudad",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Ciudad de residencia"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="curso",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Curso actual"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="motivacion",
            field=models.TextField(null=True, verbose_name="Motivación"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nombre_estudio",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Nombre de los estudios"
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="quiere_creditos",
            field=models.BooleanField(default=False, verbose_name="Quiere créditos?"),
        ),
        migrations.AlterField(
            model_name="pase",
            name="tipo_pase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pases",
                to="gestion.tipopase",
                verbose_name="Tipo de pase",
            ),
        ),
        migrations.AlterField(
            model_name="patrocinador",
            name="acreditacion",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Acreditación",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="acreditacion",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=8,
                null=True,
                unique=True,
                verbose_name="Acreditación",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="compartir_cv",
            field=models.BooleanField(
                default=False, verbose_name="Autoriza a compartir el CV"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="cv",
            field=models.FileField(
                null=True,
                upload_to=gestion.models.ruta_cv,
                validators=[
                    django.core.validators.FileExtensionValidator(["pdf"]),
                    gestion.models.validador_pdf,
                ],
                verbose_name="CV",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_aceptacion",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de aceptación"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_confirmacion_plaza",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Fecha de confirmación de la plaza",
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de registro"
            ),
        ),
        migrations.AlterField(
            model_name="persona",
            name="fecha_verificacion_correo",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Fecha de verificación del correo",
            ),
        ),
        migrations.AlterField(
            model_name="tipopase",
            name="inicio_validez",
            field=models.DateTimeField(verbose_name="Inicio de la validez"),
        ),
        migrations.AlterField(
            model_name="token",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de creación"
            ),
        ),
        migrations.AddField(
            model_name="token",
            name="fecha_expiracion",
            field=models.DateTimeField(verbose_name="Fecha de expiración"),
        ),
        migrations.AddField(
            model_name="token",
            name="fecha_uso",
            field=models.DateTimeField(
                blank=True, default=None, null=True, verbose_name="Fecha de uso"
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="fecha_rechazo_plaza",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Fecha de rechazo de la plaza",
            ),
        ),
        migrations.RemoveField(
            model_name="participante",
            name="ano_nacimiento",
        ),
        migrations.AddField(
            model_name="persona",
            name="motivo_error_correo_verificacion",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=4096,
                null=True,
                verbose_name="Motivo del error en el envío del correo de verificación",
            ),
        ),
        migrations.AddField(
            model_name="patrocinador",
            name="detalle_restricciones_alimentarias",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Detalles sobre las restricciones alimentarias",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="detalle_restricciones_alimentarias",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Detalles sobre las restricciones alimentarias",
            ),
        ),
        migrations.AlterField(
            model_name="participante",
            name="nivel_estudio",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("FORMACION_PROFESIONAL", "Formación Profesional"),
                    ("UNIVERSIDAD", "Universidad"),
                    ("MASTER", "Máster"),
                    ("OTRO", "Otro (Especificar en notas)"),
                ],
                default="OTRO",
                max_length=128,
                verbose_name="Nivel actual de estudios",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("H", "Hombre"),
                    ("M", "Mujer"),
                    ("O", "Otro"),
                    ("-", "Prefiero no decirlo"),
                ],
                default="-",
                max_length=10,
                verbose_name="Género",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="persona",
            name="talla_camiseta",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="L",
                max_length=10,
                verbose_name="Talla de la camiseta",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="participante",
            name="fecha_nacimiento",
            field=models.DateField(verbose_name="Fecha de nacimiento"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="telefono",
            field=models.CharField(max_length=16, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dni",
            field=models.CharField(max_length=9, unique=True, verbose_name="DNI"),
        ),
    ]
