# Generated by Django 5.2.8 on 2025-11-17 09:58

import django.core.validators
import django.db.models.deletion
import gestion.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gestion", "0001_sqlite_pragmas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre completo"),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "acreditacion",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="Acreditación",
                    ),
                ),
                (
                    "detalle_restricciones_alimentarias",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Detalles sobre las restricciones alimentarias",
                    ),
                ),
                (
                    "dni",
                    models.CharField(max_length=9, unique=True, verbose_name="DNI"),
                ),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("H", "Hombre"),
                            ("M", "Mujer"),
                            ("O", "Otro"),
                            ("-", "Prefiero no decirlo"),
                        ],
                        max_length=10,
                        verbose_name="Género",
                    ),
                ),
                (
                    "talla_camiseta",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("2XL", "2XL"),
                            ("3XL", "3XL"),
                        ],
                        max_length=10,
                        verbose_name="Talla de la camiseta",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        null=True,
                        upload_to=gestion.models.ruta_cv,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"]),
                            gestion.models.validador_pdf,
                        ],
                        verbose_name="CV",
                    ),
                ),
                (
                    "compartir_cv",
                    models.BooleanField(
                        default=False, verbose_name="Autoriza a compartir el CV"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de registro"
                    ),
                ),
                (
                    "fecha_verificacion_correo",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de verificación del correo",
                    ),
                ),
                (
                    "fecha_aceptacion",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de aceptación",
                    ),
                ),
                (
                    "fecha_confirmacion_plaza",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de confirmación de la plaza",
                    ),
                ),
                (
                    "fecha_rechazo_plaza",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Fecha de rechazo de la plaza",
                    ),
                ),
                (
                    "motivo_error_correo_verificacion",
                    models.TextField(
                        blank=True,
                        default=None,
                        max_length=4096,
                        null=True,
                        verbose_name="Motivo del error en el envío del correo de verificación",
                    ),
                ),
            ],
            options={
                "ordering": ["-fecha_registro"],
            },
        ),
        migrations.CreateModel(
            name="RestriccionAlimentaria",
            fields=[
                ("id_restriccion", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Restricción Alimentaria",
                "verbose_name_plural": "Restricciones Alimentarias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPase",
            fields=[
                ("id_tipo_pase", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "inicio_validez",
                    models.DateTimeField(verbose_name="Inicio de la validez"),
                ),
            ],
            options={
                "verbose_name": "Tipo de Pase",
                "verbose_name_plural": "Tipos de Pase",
                "ordering": ["inicio_validez"],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gestion.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentores",
                "abstract": False,
            },
            bases=("gestion.persona",),
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="gestion.persona",
                    ),
                ),
                ("telefono", models.CharField(max_length=16, verbose_name="Teléfono")),
                (
                    "fecha_nacimiento",
                    models.DateField(verbose_name="Fecha de nacimiento"),
                ),
                (
                    "nivel_estudio",
                    models.CharField(
                        choices=[
                            (None, ""),
                            ("FORMACION_PROFESIONAL", "Formación Profesional"),
                            ("UNIVERSIDAD", "Universidad"),
                            ("MASTER", "Máster"),
                            ("OTRO", "Otro (Especificar en notas)"),
                        ],
                        max_length=128,
                        verbose_name="Nivel actual de estudios",
                    ),
                ),
                (
                    "nombre_estudio",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Nombre de los estudios"
                    ),
                ),
                (
                    "centro_estudio",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Centro de estudios"
                    ),
                ),
                (
                    "curso",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Curso actual (si aplica)",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        max_length=128, null=True, verbose_name="Ciudad de residencia"
                    ),
                ),
                (
                    "quiere_creditos",
                    models.BooleanField(default=False, verbose_name="Quiere créditos?"),
                ),
                ("motivacion", models.TextField(null=True, verbose_name="Motivación")),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
                "permissions": [
                    ("aceptar_participante", "Aceptar Participante"),
                    ("ver_cv_participante", "Ver el CV de Participante"),
                    (
                        "ver_dni_telefono_participante",
                        "Ver el DNI y el teléfono de Participante",
                    ),
                ],
                "abstract": False,
            },
            bases=("gestion.persona",),
        ),
        migrations.AddField(
            model_name="persona",
            name="restricciones_alimentarias",
            field=models.ManyToManyField(
                blank=True,
                related_name="%(class)ss",
                to="gestion.restriccionalimentaria",
            ),
        ),
        migrations.CreateModel(
            name="Patrocinador",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=100, verbose_name="Nombre completo"),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "acreditacion",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=8,
                        null=True,
                        unique=True,
                        verbose_name="Acreditación",
                    ),
                ),
                (
                    "detalle_restricciones_alimentarias",
                    models.CharField(
                        blank=True,
                        max_length=128,
                        null=True,
                        verbose_name="Detalles sobre las restricciones alimentarias",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                (
                    "restricciones_alimentarias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="%(class)ss",
                        to="gestion.restriccionalimentaria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VERIFICACION", "Verificación correo"),
                            ("CONFIRMACION", "Confirmación plaza"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "fecha_expiracion",
                    models.DateTimeField(verbose_name="Fecha de expiración"),
                ),
                (
                    "fecha_uso",
                    models.DateTimeField(
                        blank=True, default=None, null=True, verbose_name="Fecha de uso"
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="gestion.persona",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presencia",
            fields=[
                ("id_presencia", models.AutoField(primary_key=True, serialize=False)),
                ("entrada", models.DateTimeField(blank=True, default=None, null=True)),
                ("salida", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempo_acceso",
                        to="gestion.persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presencia",
                "verbose_name_plural": "Presencias",
                "unique_together": {("persona", "entrada", "salida")},
            },
        ),
        migrations.CreateModel(
            name="Pase",
            fields=[
                ("id_pase", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="gestion.persona",
                    ),
                ),
                (
                    "tipo_pase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="gestion.tipopase",
                        verbose_name="Tipo de pase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase",
                "verbose_name_plural": "Pases",
                "ordering": ["fecha"],
                "unique_together": {("persona", "tipo_pase", "fecha")},
            },
        ),
    ]
