# Generated by Django 5.2.8 on 2025-11-20 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_initial_models"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="persona",
            options={
                "ordering": ["-fecha_registro"],
                "permissions": [
                    ("reenviar_verificacion", "Reenviar el correo de verificación"),
                    ("reenviar_confirmacion", "Reenviar el correo de confirmación"),
                ],
            },
        ),
    ]
