# Generated by Django 5.1.14 on 2025-11-16 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_sqlite_pragmas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="curso",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Curso actual (si aplica)",
            ),
        ),
    ]
