# Generated by Django 5.2.8 on 2025-11-17 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_sqlite_pragmas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patrocinador",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre completo"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre completo"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="talla_camiseta",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("2XL", "2XL"),
                    ("3XL", "3XL"),
                ],
                max_length=10,
                verbose_name="Talla de la camiseta",
            ),
        ),
    ]
