# Generated by Django 5.2.8 on 2025-12-09 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0002_initial_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentor",
            name="ciudad",
            field=models.CharField(
                max_length=128, null=True, verbose_name="Ciudad de residencia"
            ),
        ),
        migrations.AddField(
            model_name="mentor",
            name="fecha_nacimiento",
            field=models.DateField(
                default=datetime.datetime(1970, 1, 1, 0, 0),
                verbose_name="Fecha de nacimiento",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mentor",
            name="motivacion",
            field=models.TextField(null=True, verbose_name="Motivación"),
        ),
        migrations.AddField(
            model_name="mentor",
            name="quiere_creditos",
            field=models.BooleanField(default=False, verbose_name="Quiere créditos?"),
        ),
        migrations.AddField(
            model_name="mentor",
            name="telefono",
            field=models.CharField(default=0, max_length=16, verbose_name="Teléfono"),
            preserve_default=False,
        ),
    ]
