# Generated by Django 5.1.15 on 2026-01-22 23:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0004_alter_persona_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                ("id_empresa", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Empresa",
                "verbose_name_plural": "Empresas",
                "ordering": ["nombre"],
            },
        ),
        migrations.AlterModelOptions(
            name="patrocinador",
            options={
                "ordering": ["correo"],
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
            },
        ),
        migrations.AddField(
            model_name="patrocinador",
            name="comidas",
            field=models.ManyToManyField(blank=True, to="gestion.tipopase"),
        ),
        migrations.AddField(
            model_name="patrocinador",
            name="dni",
            field=models.CharField(
                default="", max_length=9, unique=True, verbose_name="DNI"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="patrocinador",
            name="fecha_registro",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Fecha de registro",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patrocinador",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gestion.empresa"
            ),
        ),
    ]
