# Generated by Django 5.2.7 on 2026-01-16 22:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_persona_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='patrocinador',
            options={'ordering': ['correo'], 'verbose_name': 'Patrocinador', 'verbose_name_plural': 'Patrocinadores'},
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='dni',
            field=models.CharField(default=None, max_length=9, unique=True, verbose_name='DNI'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patrocinador',
            name='genero',
            field=models.CharField(choices=[(None, ''), ('H', 'Hombre'), ('M', 'Mujer'), ('O', 'Otro'), ('-', 'Prefiero no decirlo')], default=django.utils.timezone.now, max_length=10, verbose_name='Género'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='gestion.empresa', verbose_name='Empresa'),
        ),
    ]
