# Generated by Django 5.2.7 on 2026-01-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_empresa_alter_patrocinador_options_patrocinador_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinador',
            name='comidas',
            field=models.ManyToManyField(blank=True, related_name='%(class)ss', to='gestion.tipopase'),
        ),
    ]
