# Generated by Django 5.1.15 on 2026-01-22 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0005_empresa_alter_patrocinador_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Patrocinador",
            new_name="Colaborador",
        ),
        migrations.AlterModelOptions(
            name="colaborador",
            options={
                "ordering": ["correo"],
                "verbose_name": "Colaborador",
                "verbose_name_plural": "Colaboradores",
            },
        ),
    ]
