# Generated by Django 5.2.10 on 2026-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0006_rename_patrocinador_colaborador_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="colaborador",
            name="telefono",
            field=models.CharField(default="", max_length=16, verbose_name="Teléfono"),
            preserve_default=False,
        ),
    ]
