# Generated by Django 5.2.8 on 2025-11-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0012_participante_ano_nacimiento_to_fecha_nacimiento"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="motivo_error_correo_verificacion",
            field=models.TextField(
                blank=True,
                default=None,
                max_length=4096,
                null=True,
                verbose_name="Motivo del error en el envío del correo de verificación",
            ),
        ),
    ]
