# Generated by Django 5.2.8 on 2025-11-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0013_persona_motivo_error_correo_verificacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="patrocinador",
            name="detalle_restricciones_alimentarias",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Detalles sobre las restricciones alimentarias",
            ),
        ),
        migrations.AddField(
            model_name="persona",
            name="detalle_restricciones_alimentarias",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Detalles sobre las restricciones alimentarias",
            ),
        ),
    ]
