# Generated by Django 5.2.8 on 2025-11-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0014_detalle_restricciones_alimentarias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[
                    ("H", "Hombre"),
                    ("M", "Mujer"),
                    ("O", "Otro"),
                    (None, "Prefiero no decirlo"),
                ],
                max_length=10,
                null=True,
                verbose_name="Género",
            ),
        ),
    ]
