# Generated by Django 5.2.8 on 2025-11-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0015_alter_persona_genero"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="nivel_estudio",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("FORMACION_PROFESIONAL", "Formación Profesional"),
                    ("UNIVERSIDAD", "Universidad"),
                    ("MASTER", "Máster"),
                    ("OTRO", "Otro (Especificar en notas)"),
                ],
                default="OTRO",
                max_length=128,
                verbose_name="Nivel actual de estudios",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="persona",
            name="genero",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("H", "Hombre"),
                    ("M", "Mujer"),
                    ("O", "Otro"),
                    ("-", "Prefiero no decirlo"),
                ],
                default="-",
                max_length=10,
                verbose_name="Género",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="persona",
            name="talla_camiseta",
            field=models.CharField(
                choices=[
                    (None, ""),
                    ("S", "S"),
                    ("M", "M"),
                    ("L", "L"),
                    ("XL", "XL"),
                    ("XXL", "XXL"),
                ],
                default="L",
                max_length=10,
                verbose_name="Talla de la camiseta",
            ),
            preserve_default=False,
        ),
    ]
