# Generated by Django 5.2.5 on 2025-11-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion", "0016_alter_participante_nivel_estudio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="fecha_nacimiento",
            field=models.DateField(verbose_name="Fecha de nacimiento"),
        ),
        migrations.AlterField(
            model_name="participante",
            name="telefono",
            field=models.CharField(max_length=16, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="dni",
            field=models.CharField(max_length=9, unique=True, verbose_name="DNI"),
        ),
    ]
