# Generated by Django 5.1.12 on 2025-09-15 23:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "correo",
                    models.EmailField(
                        max_length=254, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "dni",
                    models.CharField(blank=True, max_length=9, null=True, unique=True),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("HOMBRE", "Hombre"),
                            ("MUJER", "Mujer"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "uuid",
                    models.UUIDField(blank=True, default=None, null=True, unique=True),
                ),
                ("aceptado", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RestriccionAlimentaria",
            fields=[
                ("id_restriccion", models.AutoField(primary_key=True, serialize=False)),
                (
                    "nombre",
                    models.CharField(
                        choices=[
                            ("Vegetariano", "Vegetariano"),
                            ("Vegano", "Vegano"),
                            ("Sin gluten", "Sin gluten"),
                            ("Sin lactosa", "Sin lactosa"),
                            ("Diabético", "Diabético"),
                            ("Otro", "Otro (Especificar en notas)"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Restricción Alimentaria",
                "verbose_name_plural": "Restricciones Alimentarias",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="TipoPase",
            fields=[
                ("id_tipo_pase", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("fecha_inicio_validez", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Tipo de Pase",
                "verbose_name_plural": "Tipos de Pase",
                "ordering": ["fecha_inicio_validez"],
            },
        ),
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                (
                    "tamano_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("compartir_cv", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Mentor",
                "verbose_name_plural": "Mentores",
            },
            bases=("hackudc.persona",),
        ),
        migrations.CreateModel(
            name="Participante",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=16, null=True)),
                (
                    "ano_nacimiento",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1970, "El año debe ser mayor o igual a 1970."
                            ),
                            django.core.validators.MaxValueValidator(
                                2015, "El año debe ser menor o igual a 2015."
                            ),
                        ],
                    ),
                ),
                (
                    "nivel_estudio",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FORMACION_PROFESIONAL", "Formación Profesional"),
                            ("UNIVERSIDAD", "Universidad"),
                            ("MASTER", "Máster"),
                            ("OTRO", "Otro (Especificar en notas)"),
                        ],
                        max_length=128,
                        null=True,
                    ),
                ),
                (
                    "nombre_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                (
                    "centro_estudio",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("curso", models.CharField(blank=True, max_length=128, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=128, null=True)),
                ("quiere_creditos", models.BooleanField(default=False)),
                (
                    "talla_camiseta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "S"),
                            ("M", "M"),
                            ("L", "L"),
                            ("XL", "XL"),
                            ("XXL", "XXL"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("motivacion", models.TextField(blank=True, null=True)),
                ("compartir_cv", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Participante",
                "verbose_name_plural": "Participantes",
            },
            bases=("hackudc.persona",),
        ),
        migrations.CreateModel(
            name="Patrocinador",
            fields=[
                (
                    "persona_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="hackudc.persona",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
            },
            bases=("hackudc.persona",),
        ),
        migrations.AddField(
            model_name="persona",
            name="restricciones_alimentarias",
            field=models.ManyToManyField(
                blank=True,
                db_table="persona_restriccion_alimentaria",
                related_name="personas",
                to="hackudc.restriccionalimentaria",
            ),
        ),
        migrations.CreateModel(
            name="Presencia",
            fields=[
                ("id_presencia", models.AutoField(primary_key=True, serialize=False)),
                ("fecha_entrada", models.DateTimeField()),
                ("fecha_salida", models.DateTimeField()),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiempo_acceso",
                        to="hackudc.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Presencia",
                "verbose_name_plural": "Presencias",
                "unique_together": {("participante", "fecha_entrada", "fecha_salida")},
            },
        ),
        migrations.CreateModel(
            name="Pase",
            fields=[
                ("id_pase", models.AutoField(primary_key=True, serialize=False)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo_pase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="hackudc.tipopase",
                    ),
                ),
                (
                    "participante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pases",
                        to="hackudc.participante",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pase",
                "verbose_name_plural": "Pases",
                "ordering": ["fecha"],
                "unique_together": {("participante", "tipo_pase", "fecha")},
            },
        ),
    ]
