# Generated by Django 5.1.12 on 2025-09-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="participante",
            name="nivel_estudio",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FORMACION_PROFESIONAL", "Formación Profesional"),
                    ("UNIVERSIDAD", "Universidad"),
                    ("MASTER", "Máster"),
                    ("OTRO", "Otro"),
                ],
                help_text="Nivel de estudios en curso.",
                max_length=128,
                null=True,
            ),
        ),
    ]
