# Generated by Django 5.1.12 on 2025-09-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipopase",
            options={
                "ordering": ["inicio_validez"],
                "verbose_name": "Tipo de Pase",
                "verbose_name_plural": "Tipos de Pase",
            },
        ),
        migrations.RenameField(
            model_name="tipopase",
            old_name="fecha_inicio_validez",
            new_name="inicio_validez",
        ),
        migrations.RemoveField(
            model_name="persona",
            name="aceptado",
        ),
        migrations.AddField(
            model_name="mentor",
            name="aceptado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="participante",
            name="aceptado",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="presencia",
            name="fecha_salida",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="restriccionalimentaria",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
