# Generated by Django 5.2.5 on 2025-10-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0002_remove_persona_aceptado_persona_fecha_aceptacion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                ("token", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("VERIFICACION", "Verificación correo"),
                            ("CONFIRMACION", "Confirmación plaza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("tiempo_validez_minutos", models.PositiveIntegerField()),
                (
                    "persona",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tokens",
                        to="hackudc.persona",
                    ),
                ),
            ],
        ),
    ]
