# Generated by Django 5.1.7 on 2025-09-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackudc', '0003_participante_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='uuid',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, unique=True),
        ),
    ]
