# Generated by Django 5.1.12 on 2025-10-05 13:11

import django.core.validators
import django.db.models.deletion
import hackudc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0004_alter_persona_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="pase",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pases",
                to="hackudc.persona",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="pase",
            unique_together={("persona", "tipo_pase", "fecha")},
        ),
        migrations.RemoveField(
            model_name="pase",
            name="participante",
        ),
        migrations.AddField(
            model_name="presencia",
            name="persona",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tiempo_acceso",
                to="hackudc.persona",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="presencia",
            unique_together={("persona", "entrada", "salida")},
        ),
        migrations.RemoveField(
            model_name="presencia",
            name="participante",
        ),
    ]
