# Generated by Django 5.2.7 on 2025-11-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hackudc", "0007_alter_participante_ano_nacimiento_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token",
            name="tiempo_validez_minutos",
        ),
        migrations.AddField(
            model_name="token",
            name="fecha_expiracion",
            field=models.DateTimeField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="token",
            name="fecha_uso",
            field=models.DateTimeField(default=None, null=True, blank=True),
        ),
    ]
